apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - frontend
                topologyKey: kubernetes.io/hostname
      containers:
        - name: frontend
          image: australia-southeast1-docker.pkg.dev/shiftflow-gcp/shiftflow-repo/frontend-service:latest
          ports:
            - containerPort: 3003
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "150m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /version
              port: 3003
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /version
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          env:
            - name: AUTH_API_URL
              valueFrom:
                configMapKeyRef:
                  name: shiftflow-config
                  key: AUTH_API_URL
            - name: ADMIN_API_URL
              valueFrom:
                configMapKeyRef:
                  name: shiftflow-config
                  key: ADMIN_API_URL